# frozen_string_literal: true

ruby "~> 2.3"

source "https://rubygems.org/" do
  gemspec path: "../"

  group :development do
    gem "gh", git: "https://github.com/travis-ci/gh", ref: "38fb339510ff9ae67cb08c6df7698f4c393f5a44"
  end

  group :test do
    gem "rake", "~> 12.3"
  end
end
