# frozen_string_literal: true

ruby "~> 2.4"

source "https://rubygems.org/" do
  gemspec path: "../"

  group :test do
    gem "rake", "~> 12.3"
    gem "rbnacl", "~> 4.0"
    gem "tty-which", "~> 0.4.0"
  end
end
