# https://codeclimate.com/github/newcontext-oss/kitchen-terraform
version: "2"
plugins:
  bundler-audit:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
        - "ruby"
  fixme:
    enabled: true
  flog:
    enabled: false
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: false
exclude_patterns:
  - "doc/"
  - "docs/"
  - "examples/"
  - "spec/"
  - "test/integration"
  - "website/"
