# https://codeclimate.com/github/newcontext-oss/kitchen-terraform
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - "ruby"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
exclude_paths:
  - "examples/"
ratings:
  paths:
    - "**.md"
    - "**.rb"
    - "Gemfile.lock"
