# https://codeclimate.com/github/newcontext-oss/kitchen-terraform
engines:
  duplication:
    config:
      languages:
        - ruby
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "**.rb"
