# https://codeclimate.com/github/newcontext-oss/kitchen-terraform
version: "2"
checks:
  file-lines:
    config:
      threshold: 300
plugins:
  bundler-audit:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
        - "ruby"
  fixme:
    enabled: true
  flog:
    enabled: false
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: false
exclude_patterns:
  - "assets/"
  - "bin/"
  - "certs/"
  - "coverage/"
  - "doc/"
  - "docs/"
  - "examples/"
  - "rubygems/"
  - "source/"
  - "tmp/"
  - "vendor/"
