AllCops:
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - kitchen-terraform.gemspec
    - spec/**/*.rb
Metrics/ParameterLists:
  Exclude:
    - lib/terraform/group.rb
    - lib/terraform/plan_command.rb
