AllCops:
  DefaultFormatter: clang
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - kitchen-terraform.gemspec
    - spec/**/*.rb
Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Exclude:
    - lib/terraform/group.rb
    - lib/terraform/plan_command.rb
Style/AccessorMethodName:
  Exclude:
    - lib/terraform/command_factory.rb
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Lambda:
  EnforcedStyle: lambda
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  Exclude:
    - lib/terraform/command_options.rb
    - spec/lib/terraform/command_factory_spec.rb
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - Gemfile
    - Guardfile
    - examples/**/*
    - kitchen-terraform.gemspec
    - lib/terraform/client.rb
    - lib/terraform/command.rb
    - lib/terraform/command_factory.rb
    - lib/terraform/command_option.rb
    - lib/terraform/command_options.rb
    - lib/terraform/deprecated_output_parser.rb
    - lib/terraform/deprecated_version.rb
    - lib/terraform/get_command.rb
    - lib/terraform/no_output_parser.rb
    - lib/terraform/output_command.rb
    - lib/terraform/output_parser.rb
    - lib/terraform/prepare_input_file.rb
    - lib/terraform/project_version.rb
    - lib/terraform/shell_out.rb
    - lib/terraform/unsupported_version.rb
    - lib/terraform/validate_command.rb
    - lib/terraform/version.rb
    - lib/terraform/version_command.rb
    - spec/lib/terraform/client_spec.rb
    - spec/lib/terraform/command_factory_spec.rb
    - spec/lib/terraform/command_option_spec.rb
    - spec/lib/terraform/command_options_spec.rb
    - spec/lib/terraform/command_spec.rb
    - spec/lib/terraform/debug_logger_spec.rb
    - spec/lib/terraform/deprecated_output_parser_spec.rb
    - spec/lib/terraform/deprecated_version_spec.rb
    - spec/lib/terraform/destructive_plan_command_spec.rb
    - spec/lib/terraform/get_command_spec.rb
    - spec/lib/terraform/no_output_parser_spec.rb
    - spec/lib/terraform/output_command_spec.rb
    - spec/lib/terraform/output_parser_spec.rb
    - spec/lib/terraform/plan_command_spec.rb
    - spec/lib/terraform/prepare_input_file_spec.rb
    - spec/lib/terraform/prepare_output_file_spec.rb
    - spec/lib/terraform/shell_out_spec.rb
    - spec/lib/terraform/show_command_spec.rb
    - spec/lib/terraform/unsupported_version_spec.rb
    - spec/lib/terraform/validate_command_spec.rb
    - spec/lib/terraform/version_command_spec.rb
    - spec/lib/terraform/version_spec.rb
    - spec/spec_helper.rb
    - spec/support/coverage.rb
    - spec/support/raise_error_examples.rb
    - spec/support/terraform/command_examples.rb
    - spec/support/yield_control_examples.rb
Style/WordArray:
  EnforcedStyle: brackets
