AllCops:
  DefaultFormatter: clang
  DisplayCopNames: true
  TargetRubyVersion: 2.2
Layout/IndentArray:
  Enabled: false
Layout/IndentHash:
  Enabled: false
  EnforcedStyle: align_braces
Layout/IndentHeredoc:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Lambda:
  EnforcedStyle: lambda
Style/MultilineBlockChain:
  Enabled: false
Style/MutableConstant:
  Exclude:
    - lib/terraform/project_version.rb
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
  EnforcedStyle: slashes
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
