---
driver:
  name: terraform
  lock_timeout: 5
  plugin_directory: Plugin Directory
  variable_files:
    - Variable Files/Variable File.tfvars
  variables:
    docker_container_name: Ub.nt.-C.nt..n.r

provisioner:
  name: terraform

transport:
  name: ssh
  password: root

verifier:
  name: terraform
  groups:
    - name: container
      controls:
        - operating_system
      port: 2222
      hostnames: hostnames
    - name: localhost
      controls:
        - state_files

platforms:
  - name: ubuntu

suites:
  - name: example
