---
driver:
  name: terraform
provisioner:
  name: terraform
  variable_files:
    - test/fixtures/credentials.tfvars
transport:
  name: ssh
  connection_retries: 76
verifier:
  name: terraform
  format: doc
  groups:
    - name: contrived
      attributes:
        overridden_security_group: security_group
      controls:
        - reachable_other_host
        - running_service
        - security_group
      hostnames: contrived_hostnames
      port: 22
      username: ubuntu
platforms:
  - name: ubuntu
suites:
  - name: example
