---
driver:
  name: terraform
provisioner:
  name: terraform
  directory: >-
    test/fixtures/<%= `terraform -version`.slice(/v(\d+\.\d+)/, 1) %>
transport:
  name: ssh
  connection_retries: 76
verifier:
  name: terraform
  format: doc
  groups:
    - name: contrived
      attributes:
        overridden_security_group: security_group
      controls:
        - reachable_other_host
        - remote_security_group
        - running_service
      hostnames: contrived_hostnames
      port: 22
      username: ubuntu
    - name: local
      controls:
        - local_security_group
platforms:
  - name: ubuntu
suites:
  - name: example
