---
driver:
  name: "terraform"
  directory: "test/fixtures/us_east_1"
  parallelism: 4
provisioner:
  name: "terraform"
transport:
  name: "ssh"
verifier:
  name: "terraform"
  groups:
    -
      name: "remote"
      attributes:
        overridden_security_group: "security_group"
      controls:
        - "reachable_other_host"
        - "remote_security_group"
        - "running_service"
      hostnames: "test_target_public_dns"
      port: 22
      username: "ubuntu"
    -
      name: "local"
      controls:
        - "local_security_group"
        - "state_file"
platforms:
  -
    name: "ubuntu"
suites:
  -
    name: "example"
