---
driver:
  name: terraform
  directory: test/fixtures/<%= `terraform -version`.include? '0.7' and 'deprecated' or 'supported' %>
  parallelism: 4
provisioner:
  name: terraform
transport:
  name: ssh
  connection_retries: 76
verifier:
  name: terraform
  format: doc
  groups:
    - name: contrived
      attributes:
        overridden_security_group: security_group
      controls:
        - reachable_other_host
        - remote_security_group
        - running_service
      hostnames: contrived_hostnames
      port: 22
      username: ubuntu
    - name: local
      controls:
        - local_security_group
        - state_file
platforms:
  - name: ubuntu
suites:
  - name: example
