---
driver:
  name: "terraform"
  command_timeout: 1000
  variable_files:
    - "./my-variables.tfvars"
provisioner:
  name: "terraform"
transport:
  name: "ssh"
  ssh_key: "./dummy_keypair/cloud.key"
  username: "ubuntu"
verifier:
  name: "terraform"
  groups:
    -
      name: "master"
      controls:
        - "nano_installed"
      hostnames: "master_address"
    -
      name: "workers"
      controls:
        - "curl_installed"
      hostnames: "workers_addresses"
platforms:
  - name: "ubuntu"
suites:
  - name: "example"
