---
driver:
  name: terraform

provisioner:
  name: terraform
  variables:
    docker_host: "unix:///var/run/docker.sock"
    docker_container: "terraform"
    docker_image: "rastasheep/ubuntu-sshd:latest"

platforms:
  - name: terraform

transport:
  name: ssh
  password: root 

suites:
  - name: default

verifier:
  name: terraform 
  format: doc
  groups:
  - name: default
    tests:
      - operating_system
    port: 2222
    hostnames: localhost
