---
driver:
  name: terraform
  variables:
    docker_host: "unix:///var/run/docker.sock"
    docker_container: "terraform"
    docker_image: "rastasheep/ubuntu-sshd:latest"

provisioner:
  name: terraform

transport:
  name: ssh
  password: root

verifier:
  name: terraform
  format: doc
  groups:
    - name: default
      controls:
        - operating_system
      port: 2222
      hostnames: localhost

platforms:
  - name: terraform

suites:
  - name: default
