# frozen_string_literal: true

source "https://rubygems.org/" do
  # awspec will be required to test AWS resources until Kitchen-Terraform supports
  # the AWS InSpec backend
  gem(
    "awspec",
    "~> 1.5"
  )

  gem(
    "kitchen-terraform",
    "~> 3.3"
  )
end
