source 'https://rubygems.org'

gem 'middleman', '~> 4.2'

# Platforms are needed as middleman fails without them
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]

# HTML presentation
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-favicon-maker', '~> 4.1'
gem 'middleman-syntax', '~> 3.0'

# Reloads middleman server content
gem 'middleman-livereload', '~> 3.4'

# Speed up livereloads when running middleman server
gem 'mini_racer', '~> 0.1'
