name: Delivery Pipeline

on:
  push:
  pull_request:

jobs:
  commit-stage:
    name: "Commit Stage"
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: '2.4'
          bundler-cache: true
      - name: Run RSpec Tests
        if: ${{ matrix.ruby-version != '3.2' }}
        run: bundle exec rake test:rspec
      - name: Run RSpec Tests with Code Coverage
        if: ${{ matrix.ruby-version == '3.2' }}
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 7574433e1beed630cb9a171c688bb9e010d5028f00f7218d6e845fe138c65168
        with:
          coverageCommand: bundle exec rake test:rspec
      - name: Build Ruby Gem
        if: ${{ matrix.ruby-version == '3.2' }}
        env:
          GEM_PRIVATE_KEY: ${{ secrets.GEM_PRIVATE_KEY }}
        run: |
          printf -- "${GEM_PRIVATE_KEY}\n" > certs/gem-private_key.pem
          gem cert --add certs/gem-public_cert.pem
          gem build kitchen-terraform.gemspec --strict --output kitchen-terraform.gem
      - name: Upload Ruby Gem
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v3
        with:
          name: ruby-gem
          path: kitchen-terraform.gem
