name: Delivery

concurrency: delivery-${{ github.ref }}

on:
  - push

jobs:
  commit:
    name: "Commit"
    if: ${{ github.ref_type == 'branch' }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: '2.4'
          bundler-cache: true
      - name: Run RSpec Tests
        if: ${{ matrix.ruby-version != '3.1' }}
        run: bundle exec rake test:rspec
      - name: Run RSpec Tests with Code Coverage
        if: ${{ matrix.ruby-version == '3.1' }}
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 7574433e1beed630cb9a171c688bb9e010d5028f00f7218d6e845fe138c65168
        with:
          coverageCommand: bundle exec rake test:rspec
      - name: Initialize CodeQL
        if: ${{ matrix.ruby-version == '3.1' }}
        uses: github/codeql-action/init@v2
        with:
          config-file: .github/codeql/config.yml
          languages: ruby
      - name: Perform CodeQL Analysis
        if: ${{ matrix.ruby-version == '3.1' }}
        uses: github/codeql-action/analyze@v2
      - name: Build Ruby Gem
        if: ${{ matrix.ruby-version == '3.1' }}
        env:
          GEM_PRIVATE_KEY: ${{ secrets.GEM_PRIVATE_KEY }}
        run: |
          printf -- "${GEM_PRIVATE_KEY}\n" > certs/gem-private_key.pem
          gem cert --add certs/gem-public_cert.pem
          gem build kitchen-terraform.gemspec --strict --output kitchen-terraform.gem
      - name: Upload Ruby Gem
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && matrix.ruby-version == '3.1' }}
        uses: actions/upload-artifact@v3
        with:
          name: ruby-gem
          path: kitchen-terraform.gem

  acceptance:
    name: "Acceptance"
    if: ${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name == 'main' }}
    needs:
      - commit
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: macos
            terraform-version: '1.1.4'
            terragrunt-version: '0.36.0'
          - operating-system: ubuntu
            terraform-version: '0.15.5'
          - operating-system: ubuntu
            terraform-version: '0.14.11'
          - operating-system: windows
            terraform-version: '0.13.7'
    runs-on: ${{ matrix.operating-system }}-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
      - name: Download Ruby Gem
        uses: actions/download-artifact@v3
        with:
          name: ruby-gem
      - name: Install Ruby Gems
        run: gem install --conservative --minimal-deps --verbose kitchen-terraform.gem rake
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - name: Setup Terragrunt
        if: ${{ matrix.operating-system == 'macos' }}
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: ${{ matrix.terragrunt-version }}
      - name: Mirror Terraform Providers
        run: |
          cd ./test/terraform/PlugIns
          terraform providers mirror ./PlugInDirectory
      - name: Run Kitchen Tests
        run: |
          rake test:kitchen:attributes-${{ matrix.operating-system }}
          rake test:kitchen:plug-ins-${{ matrix.operating-system }}
          rake test:kitchen:variables-${{ matrix.operating-system }}
          rake test:kitchen:workspaces-${{ matrix.operating-system }}
      - name: Run Kitchen Test backend-ssh
        if: ${{ matrix.operating-system == 'ubuntu' }}
        run: |
          chmod 400 ./test/terraform/$VERSION_MATCHER/backend-ssh/id_ed25519
          rake test:kitchen:backend-ssh-ubuntu
      - name: Run Kitchen doctor
        run: |
          status=0
          output="$(kitchen doctor doctor)"
          if [[ $output != *"${{ matrix.operating-system }}.driver.client"* ]]
          then
            echo "kitchen doctor did not detect driver.client error"
            status=1
          fi
          if [[ $output != *"${{ matrix.operating-system }}.verifier.systems"* ]]
          then
            echo "kitchen doctor did not detect verifier.systems error"
            status=1
          fi
          exit $status

  release:
    name: "Release"
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false
    - name: Download Ruby Gem
      uses: actions/download-artifact@v3
      with:
        name: ruby-gem
        path: kitchen-terraform.gem
    - name: Publish
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      run: gem push kitchen-terraform.gem
