name: Kitchen Tests

on: pull_request

jobs:
  kitchen-tests:
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - macos
          - ubuntu
          - windows
        terraform-version:
          - '0.13.7'
          - '0.14.11'
          - '0.15.5'
          - '1.0.1'
    runs-on: ${{ matrix.operating-system }}-latest
    env:
      VERSION_MATCHER: ${{ fromJSON('["pre-0-15-0", "post-0-15-0"]')[matrix.terraform-version == '0.15.5' || matrix.terraform-version == '1.0.1'] }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          # bundler 2.2 fails to install the gems
          bundler: '2.1.4'
          bundler-cache: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - name: Setup Homebrew
        if: ${{ matrix.operating-system == 'macos' }}
        uses: homebrew/actions/setup-homebrew@master
      - name: Install Terragrunt
        if: ${{ matrix.operating-system == 'macos' }}
        run: |
          brew install terragrunt
      - name: Mirror Terraform Providers
        run: |
          cd ./tests/terraform/$VERSION_MATCHER/PlugIns
          terraform providers mirror ./PlugInDirectory
      - name: Run Kitchen Tests
        run: |
          bundle exec rake test:kitchen:attributes-$VERSION_MATCHER-${{ matrix.operating-system }}
          bundle exec rake test:kitchen:plug-ins-$VERSION_MATCHER-${{ matrix.operating-system }}
          bundle exec rake test:kitchen:variables-$VERSION_MATCHER-${{ matrix.operating-system }}
          bundle exec rake test:kitchen:workspaces-$VERSION_MATCHER-${{ matrix.operating-system }}
      - name: Run Kitchen Test backend-ssh
        if: ${{ matrix.operating-system == 'ubuntu' }}
        run: |
          chmod 400 ./test/terraform/$VERSION_MATCHER/backend-ssh/id_ed25519
          bundle exec rake test:kitchen:backend-ssh-$VERSION_MATCHER-ubuntu