name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false # when true, runs 'bundle install' and caches installed gems automatically

    - name: Build
      run: |
        printf -- "${GEM_PRIVATE_KEY}\n" > certs/gem-private_key.pem
        gem cert --add certs/gem-public_cert.pem
        gem build kitchen-terraform.gemspec --silent
      env:
        GEM_PRIVATE_KEY: ${{ secrets.GEM_PRIVATE_KEY }}

    - name: Publish
      run: |
        gem update --system
        RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        gem push kitchen-terraform-${RELEASE_VERSION}.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
