name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Build
      if: github.event.base_ref == 'refs/heads/master'
      run: |
        printf -- "${GEM_PRIVATE_KEY}\n" > $HOME/certs/gem-private_key.pem
        gem cert --add certs/gem-public_cert.pem
        gem build kitchen-terraform.gemspec --silent
      env:
        GEM_PRIVATE_KEY: ${{ secrets.GEM_PRIVATE_KEY }}

    - name: Publish
      if: github.event.base_ref == 'refs/heads/master'
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        gem push kitchen-terraform-${RELEASE_VERSION}.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
